apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
  namespace: mydemo1ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
      annotations:
        gke-gcsfuse/volumes: "true" # this annotations must be use for the pods !!!
    spec:
      serviceAccountName: mydemo1sa
      containers:
        - name: myapp1-container
          image: ghcr.io/stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
          - name: gcs-fuse-csi-static
            mountPath: /usr/share/nginx/html
            readOnly: true  # just read
      volumes:
      - name: gcs-fuse-csi-static
        persistentVolumeClaim:
          claimName: gcs-fuse-csi-static-pvc