apiVersion: v1
kind: Pod
metadata:
  name: filestore-writer-app
  labels:
    type: writer-pod
spec:
  containers:
    - name: app
      image: centos  #
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo GCP Cloud FileStore used as PV in GKE $(date -u) >> /data/myapp1.txt; sleep 5; done"]
      volumeMounts:
        - name: my-filestore-storage
          mountPath: /data
  volumes:
    - name: my-filestore-storage
      persistentVolumeClaim:
        claimName: gke-filestore-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata: #Dictionary
  name: myapp1-deployment
spec: # Dictionary
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata: # Dictionary
      name: myapp1-pod
      labels: # Dictionary
        app: myapp1  # Key value pairs
        type: reader-pod
    spec:
      containers: # List
        - name: myapp1-container
          image: ghcr.io/stacksimplify/kubenginx:1.0.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: persistent-storage
              mountPath: /usr/share/nginx/html/filestore
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: gke-filestore-pvc
